
services:
  app:
    build:
        dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: todo
      DB_PASSWORD: todoMySQLPassword
      DB_NAME: todo_data

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_data
      MYSQL_USER: todo
      MYSQL_PASSWORD: todoMySQLPassword
    volumes:
      - db_data:/var/lib/mysql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
